### ISSUE TITLE
How to download the pretrained models?

### ISSUE THREAD

**Issue by GPhilo** [TongkunGuan/RFN#3]
Hello,

I'm trying to download the pretrained models to test them, but I don't know how.
The links redirect to a Baidu page, but attempting to download the file asks to download Baidu's client (in Chinese only) and I don't knwo how to go from there.
Is there an option to download the files without having to use Baidu's client?

**Comment by TongkunGuan** [comment]
I suggest you download the Baidu client. 
Link: https://issuepcdn.baidupcs.com/issue/netdisk/LinuxGuanjia/4.3.0/baidunetdisk_4.3.0_amd64.deb.
Or you can wait for me, and I will try other ways to upload it in my spare time.

**Comment by GPhilo** [comment]
Hello,

Thank you for your reply. I tried using the (Windows) client, but once installed I had no clue of how to proceed, as it's in Chinese and ai couldn't find a way to change the language.
I did manage to download the file in a different way, however.
