### ISSUE TITLE
icdar2013index

### ISSUE THREAD

**Issue by 123cjjjj** [TongkunGuan/RFN#5]
geo_map_loc = self.encoder.anchor_quad_boxes[cls_index_i].cuda() + loc_preds_all[i, cls_index_i,
IndexError: index 167807 is out of bounds for dimension 0 with size 152880

**Comment by TongkunGuan** [comment]
please show a detailed description of the issue

**Comment by 123cjjjj** [comment]
Modify the dataset of relevant files according to the steps in "configuring your dataset" (instead of using ustb-sv1k dataset in the source code , we attempt to use icdar2013 for training).but it failed, The error messages are as follows:




Traceback (most recent call last):
  File "train.py", line 221, in <module>
    loc_preds,cls_preds,gts_preds,detector_losses,recur_proposals = net((inputs,target_polyons))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/data/private/0801RFN/RFN/tools/model.py", line 750, in forward
    geo_map_loc = self.encoder.anchor_quad_boxes[cls_index_i].cuda() + loc_preds_all[i, cls_index_i,
IndexError: index 167807 is out of bounds for dimension 0 with size 152880


 







At 2022-08-07 13:55:08, "TongkunGuan" ***@***.***> wrote:

please show a detailed description of the issue

**Comment by TongkunGuan** [comment]
Modify some settings in $RFN_ROOT/tools/encoder.py, including anchor_areas, aspect_ratios.

**Comment by 123cjjjj** [comment]
Thank you for your reply. This problem has been solved successfully.











At 2022-08-10 21:19:38, "TongkunGuan" ***@***.***> wrote:

Modify some settings in $RFN_ROOT/tools/encoder.py, including anchor_areas, aspect_ratios.
