### ISSUE TITLE
SynthText dataset pretrained model

### ISSUE THREAD

**Issue by 123cjjjj** [TongkunGuan/RFN#7]
Will the pretrained model obtained by training the RFN model on the SynthText dataset be opened?

**Comment by TongkunGuan** [comment]
![image](https://user-images.githubusercontent.com/51256562/196023289-9c831cae-92d9-4904-8ecb-9bb6276cfe3e.png)

**Comment by 123cjjjj** [comment]
感谢回复。这个预训练模型是在MPSC数据集上训练得到吧？我们想使用ICDAR2013作为目标数据集，文章中提到ICDAR2013使用的预训练模型是由SynthText数据集训练得到的，这个预训练模型会公布吗？









在 2022-10-16 15:15:45，"TongkunGuan" ***@***.***> 写道：

**Comment by 123cjjjj** [comment]
你好，我们想使用ICDAR2013作为目标数据集，文章中提到ICDAR2013使用的预训练模型是由SynthText数据集在该网络上训练得到的，请问这个预训练模型会公布吗？

**Comment by TongkunGuan** [comment]
我有时间会整理一下放出来 你可以自己先训练一下~

**Comment by TongkunGuan** [comment]
> 你好，我们想使用ICDAR2013作为目标数据集，文章中提到ICDAR2013使用的预训练模型是由SynthText数据集在该网络上训练得到的，请问这个预训练模型会公布吗？

我有时间会整理一下放出来 你可以自己先训练一下~

**Comment by TongkunGuan** [comment]
> 你好，我们想使用ICDAR2013作为目标数据集，文章中提到ICDAR2013使用的预训练模型是由SynthText数据集在该网络上训练得到的，请问这个预训练模型会公布吗？

已释放 请关注 如果对你的工作有帮助 请记得引用我们的工作 谢谢~
