### ISSUE TITLE
No module named tools

### ISSUE THREAD

**Issue by k-styles** [TongkunGuan/RFN#9]
I am following INSTALL.md README file, my python version is 3.6.2, and all other libraries are the same as used here. However, I am using 11.3 nvidia toolkit.

I get this error when I try to run: `python ./tools/get_state_dict.py`
```
Traceback (most recent call last):
  File "./tools/get_state_dict.py", line 18, in <module>
    from model import RFN
  File "/Data/home/ug19/1903123/BTPs/text_spotting/RFN/tools/model.py", line 12, in <module>
    from tools.fpn import FPN50
ModuleNotFoundError: No module named 'tools'
```

Any idea, what might be going wrong?

**Comment by TongkunGuan** [comment]
try：from fpn import FPN50

> I am following INSTALL.md README file, my python version is 3.6.2, and all other libraries are the same as used here. However, I am using 11.3 nvidia toolkit.
> 
> I get this error when I try to run: `python ./tools/get_state_dict.py`
> 
> ```
> Traceback (most recent call last):
>   File "./tools/get_state_dict.py", line 18, in <module>
>     from model import RFN
>   File "/Data/home/ug19/1903123/BTPs/text_spotting/RFN/tools/model.py", line 12, in <module>
>     from tools.fpn import FPN50
> ModuleNotFoundError: No module named 'tools'
> ```
> 
> Any idea, what might be going wrong?

Try: from fpn import FPN50
